### ISSUE TITLE
Error in Plausible service

### ISSUE THREAD

**Issue by sangdth** [railwayapp-templates/plausible#1] opened 2023-11-10 06:31 UTC
Steps I did:

- Create new service with Plausible template
- Wait for deployment finish.
- Check the logs.
- The Plausible app can not reach. (Application failed to respond)

```
** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
(plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0
(elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
(plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0
nofile:1: (file)
(stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
```

**Comment by MykalMachon** [comment] 2023-11-12 01:50
Hi @sangdth, thanks for submitting an issue!

Based on the steps you've described, _it sounds like you may have missed our quick start guide._

The quick start guide can be found in this repo's README or the template description on Railway. There are some manual steps you have to take to properly set the environment variables with this template. 

I realize that's not ideal, but the Railway team is aware of it and working on it last I heard!

**Comment by brody192** [comment] 2023-11-12 03:40
The issue the quick start references where you need to re-save the variables has been fixed a while ago

**Comment by MykalMachon** [comment] 2023-11-12 05:43
> The issue the quick start references where you need to re-save the variables has been fixed a while ago

Oh good to know! Thanks @brody192. I will update the README here and on Railway.

**Comment by brody192** [comment] 2023-11-12 05:54
that just leaves the error sang opened

**Comment by MykalMachon** [comment] 2023-11-12 05:55
> Steps I did:
> 
> * Create new service with Plausible template
> * Wait for deployment finish.
> * Check the logs.
> * The Plausible app can not reach. (Application failed to respond)
> 
> ```
> ** (MatchError) no match of right hand side value: {:error, %Mint.TransportError{reason: :nxdomain}}
> (plausible 0.0.1) lib/plausible_release.ex:40: anonymous fn/2 in Plausible.Release.createdb/0
> (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
> (plausible 0.0.1) lib/plausible_release.ex:39: Plausible.Release.createdb/0
> nofile:1: (file)
> (stdlib 4.2) erl_eval.erl:748: :erl_eval.do_apply/7
> ```

Alright! I did some experimentation and saw the same error. **All I had to do to fix it was:** 
1. Wait for the Clickhouse DB service to fully spin up 
2. Restart the Plausible Analytics web app service
3. Plausible analytics is then able to connect and works as expected. 

**@sangdth can you try restarting the plausible analytics service while your ClickHouse service is up and report back?**

It looks like the problem is that the Plausible service is coming up before the ClickHouse service, so it can't connect (which makes sense).

@brody192 are you aware of any way to add a `depends_on: clickhouse_db` to the PA Web Service? I know in the past you suggested building in a `sleep 100 && ./entrypoint.sh` style strategy for the entrypoint script for the plausible service but that is hacky at best. Ideally I could wait until the clickhouse service is deployed to spin up the plausible service, but doesn't seem possible on the platform yet.

**Comment by brody192** [comment] 2023-11-12 06:12
`depends_on` is not unfortunately possible, The next best thing would be to add a [wait-for-it](https://github.com/vishnubob/wait-for-it) script to the start command instead of the `sleep 100` you showed

**Comment by MykalMachon** [comment] 2023-11-12 07:27
Alright, so I should be able to do something _like_ below for the startup command:
```bash
sh -c "echo 'Waiting for ClickHouse DB service to start...' && curl -s https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait.sh && chmod +x wait.sh && ./wait.sh -t 360 -h clickhouse -p 8123 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
```
The plausible analytics image doesn't have curl though. So I'll either have to repackage the image myself, or find another clever solution. 

I'll think it over tonight and see if I can find a good way to do that without having to build my own plausible image on railway which frankly doesn't seem like a great idea for template maintainability in the long-term.

**Comment by MykalMachon** [comment] 2023-11-12 07:55
> Alright, so I should be able to do something _like_ below for the startup command:
> 
> ```shell
> sh -c "echo 'Waiting for ClickHouse DB service to start...' && curl -s https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait.sh && chmod +x wait.sh && ./wait.sh -t 360 -h clickhouse -p 8123 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
> ```
> 
> The plausible analytics image doesn't have curl though. So I'll either have to repackage the image myself, or find another clever solution.
> 
> I'll think it over tonight and see if I can find a good way to do that without having to build my own plausible image on railway which frankly doesn't seem like a great idea for template maintainability in the long-term.

Found a fix using a builtin command, `nc`
```bash
sh -c "while ! nc -z clickhouse 8123 ; do sleep 5 ; done && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
```
I'll update the template now, and close off this issue once it's done. I'm also going to make another issue for fixing the docs.

**Comment by brody192** [comment] 2023-11-12 07:59
awesome, using `nc` directly is a great solution, you also could have included that script I linked in this repo

**Comment by MykalMachon** [comment] 2023-11-12 08:23
Validated the template as fixed; going to close this issue. 
@sangdth if you're still having issues here are some final remediation steps:

1. Restart your plausible instance
2. Redeploy the template (assuming you never got your first attempt working), the new config changes I just made should resolve this issue.

**Closed as completed by MykalMachon** 2023-11-12 08:23 UTC
Labels: bug, question
